<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Converty.Contracts/Converty.Contracts.csproj" />
    <ProjectReference Include="../Converty.Serialization/Converty.Serialization.csproj" />
  </ItemGroup>
</Project>
