<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Converty.Contracts/Converty.Contracts.csproj" />
    <ProjectReference Include="../Converty.Ipc/Converty.Ipc.csproj" />
    <ProjectReference Include="../Converty.Security/Converty.Security.csproj" />
    <ProjectReference Include="../Converty.Serialization/Converty.Serialization.csproj" />
  </ItemGroup>
</Project>
