<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Converty.Bridge/Converty.Bridge.csproj" />
    <ProjectReference Include="../../src/Converty.Contracts/Converty.Contracts.csproj" />
    <ProjectReference Include="../../src/Converty.Ipc/Converty.Ipc.csproj" />
    <ProjectReference Include="../../src/Converty.Security/Converty.Security.csproj" />
    <ProjectReference Include="../../src/Converty.Serialization/Converty.Serialization.csproj" />
  </ItemGroup>
</Project>
