<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <Description>Disposable Converty conversion engine worker.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Converty.Core/Converty.Core.csproj" />
    <ProjectReference Include="../../providers/Converty.Provider.FFmpeg/Converty.Provider.FFmpeg.csproj" />
  </ItemGroup>
</Project>
